name: Deploy FastAPI App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Docker
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_NAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Navigate to the deployment directory
          if [ ! -d "fastapi-docker" ]; then
            git clone git@github.com:ItamarShalev/web_api_server.git
            cd fastapi-docker
          else
            cd web_api_server
            git pull
          fi
          
          docker-compose down
          docker-compose up --build -d
          EOF
